---
- hosts: localhost

  tasks:
  - name: Create a VPC
    ec2_vpc_net:
     #aws_access_key: "{{ec2_access_key}}"
     #aws_secret_key: "{{ec2_secret_key}}"
      name: test_vpc
      cidr_block: "192.168.0.0/16"
      region: "ap-southeast-2"
      state: "{{ state | default('present') }}"
