---
- hosts: localhost

  tasks:
  - name: Get EC2 info
    ec2_instance_info:
      region: "{{ region }}"
    register: EC2_info

  - name: Terminate instances that were previously launched
    ec2:
      region: "{{ region }}"
      state: "absent"
      instance_ids: "{{ item.instance_id }}"
    loop: "{{ EC2_info.instances }}"
    when: item.state.name == "running"

  - name: Pause 5 mins until EC2 instances terminated
    pause:
      minutes: 5

  - name: Get VPC information
    ec2_vpc_net_info:
      region: "{{ region }}"
      filters:
        "tag:Name": "{{ vpc_name }}"
    register: vpc_info

  - name: Get Public Subnet information
    ec2_vpc_subnet_info:
      region: "{{ region }}"
      filters:
        vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": public
    register: subnet_info

  - name: Gather Route Table information
    ec2_vpc_route_table_info:
      region: "{{ region }}"
      filters:
        association.subnet-id: "{{ subnet_info.subnets[0].subnet_id }}"
    register: rt_info

  - name: Delete Public Subnet
    ec2_vpc_subnet:
      region: "{{ region }}"
      az: "{{ availability_zone }}"
      cidr: "{{ publlic_ipv4_cidr }}"
      ipv6_cidr: "{{ publlic_ipv6_cidr }}"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      map_public: yes
      tags:
        Name: "public"
      state: absent
          
  - name: Delete Private Subnet
    ec2_vpc_subnet:
      region: "{{ region }}"
      az: "{{ availability_zone }}"
      cidr: "{{ private_ipv4_cidr }}"
      ipv6_cidr: "{{ private_ipv6_cidr }}"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      map_public: no
      tags:
        Name: "private"
      state: absent

  - name: Delete Route Table
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      region: "{{ region }}"
      route_table_id: "{{ rt_info.route_tables[0].id }}"
      lookup: id
      state: absent

  - name: Delete Internet Gateway
    ec2_vpc_igw:
      region: "{{ region }}"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      state: absent

  - name: Delete security group
    ec2_group:
      region: "{{ region }}"
      name: "{{ SG }}"
      state: absent

  - name: Delete VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ cidr_block }}"
      region: "{{ region }}"
      state: absent
