---
- hosts: localhost

  tasks:
    - name: Test the jumphost
      include: tests/test_jumphost.yml

    - name: Test the web server
      include: tests/test_web.yml

    - name: Test the private host
      include: tests/test_private.yml
...
