---
- hosts: localhost

  tasks: 
  - name: create a VPC
    shell:
      aws ec2 create-vpc --cidr-block {{ cidr_block }} --amazon-provided-ipv6-cidr-block

  - name: Query VPC info
    ec2_vpc_net_info:
      region: "{{ region }}"
    register: vpc_info
 
  - name: name the VPC
    shell:
      aws ec2 create-tags --resources {{ item.vpc_id }} --tags Key=Name,Value={{ vpc_name }} 
    loop: "{{ vpc_info.vpcs }}"
    when: item.cidr_block == "{{ cidr_block }}"
...
