---
- hosts: localhost

  tasks:
  - name: Get EC2 info
    ec2_instance_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
    register: EC2_info

  - name: Terminate instances that were previously launched
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      state: "absent"
      instance_ids: "{{ item.instance_id }}"
    loop: "{{ EC2_info.instances }}"
    when: item.state.name == "running"

  - name: Pause 5 mins until EC2 instances terminated
    pause:
      minutes: 5

  - name: Get EIP information
    ec2_eip_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
    register: eip_info

  - name: Get VPC information
    ec2_vpc_net_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": vpc_web
    register: vpc_info

  - name: Get Public Subnet information
    ec2_vpc_subnet_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": public
    register: subnet_info

  - name: Gather Route Table information
    ec2_vpc_route_table_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        association.subnet-id: "{{ subnet_info.subnets[0].subnet_id }}"
    register: rt_info
        
  - name: Release EIP
    ec2_eip:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      device_id: "{{ eip_info.addresses[0].network_interface_id }}"
      ip: "{{ eip_info.addresses[0].public_ip }}"
      in_vpc: yes
      release_on_disassociation: yes
      state: absent

  - name: Delete ENI
    ec2_eni:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      eni_id: "{{ eip_info.addresses[0].network_interface_id }}"
      state: absent

  - name: Delete Public Subnet
    ec2_vpc_subnet:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      az: "ap-southeast-2a"
      cidr: "192.168.1.0/24"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      map_public: yes
      tags:
        Name: "public"
      state: absent
          
  - name: Delete Private Subnet
    ec2_vpc_subnet:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      az: "ap-southeast-2a"
      cidr: "192.168.2.0/24"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      map_public: no
      tags:
        Name: "private"
      state: absent

  - name: Delete Route Table
    ec2_vpc_route_table:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      region: "ap-southeast-2"
      route_table_id: "{{ rt_info.route_tables[0].id }}"
      lookup: id
      state: absent

  - name: Delete Internet Gateway
    ec2_vpc_igw:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      state: absent

  - name: Delete VPC
    ec2_vpc_net:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      name: vpc_web
      cidr_block: "192.168.0.0/16"
      region: "ap-southeast-2"
      state: absent
