---
- hosts: localhost

  tasks:
  - name: get jumphost EC2 info
    ec2_instance_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": jumphost
    register: jumphost_info
        
  - name: get private EC2 info
    ec2_instance_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": private
    register: private_info
 
  - name:  SSH from jumphost to private host
    shell: 
       ssh -i /home/ubuntu/web-keypair.pem ubuntu@"{{ private_info.instances[0].public_dns_name}}"
       exit
    delegate_to: "{{ jumphost_info.instances[0].public_dns_name }}"


  - name:  SSH from internet to private host
    command: ssh -i "{{ ansible_ssh_private_key_file }}" "{{ ansible_ssh_user }}"@"{{ private_info.instances[0].public_dns_name}}"
    register: private_ssh_internet
