---
- hosts: localhost

  tasks:
  - name: get web EC2 info
    ec2_instance_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": web
    register: web_info

  - name:  ssh to web server
    command: ssh -i "{{ ansible_ssh_private_key_file }}" "{{ ansible_ssh_user }}"@"{{ item.public_dns_name }}"
    loop: "{{ web_info.instances }}"
    when: item.state.name == "running"
    register: web_ssh_prompt

  - name:  check if able to connect (GET) to a page and it returns a status 200
    uri:
      url: "http://{{ item.public_dns_name }}"
      status_code: 200
    loop: "{{ web_info.instances }}"
    when: item.state.name == "running" 
