---
- hosts: localhost

  tasks:
  - name: Get EC2 info
    ec2_instance_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": web
    register: EC2_info

  - name: Terminate instances that were previously launched
    ec2:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      state: "absent"
      instance_ids: "{{ item.instance_id }}"
    loop: "{{ EC2_info.instances }}"
    when: item.state.name == "running"

  - name: Pause 5 mins until EC2 terminated
    pause:
      minutes: 5

  - name: Get VPC information
    ec2_vpc_net_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": vpc_web
    register: vpc_info

  - name: Get Subnet information
    ec2_vpc_subnet_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        vpc-id: "{{ vpc_info.vpcs[0].vpc_id }}"
        "tag:Name": public
    register: subnet_info

  - name: Gather Route Table information
    ec2_vpc_route_table_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        association.subnet-id: "{{ subnet_info.subnets[0].subnet_id }}"
    register: rt_info 
        
  - name: Delete Public Subnet
    ec2_vpc_subnet:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      az: "ap-southeast-2a"
      cidr: "192.168.1.0/24"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      map_public: yes
      tags:
        Name: "public"
      state: absent

  - name: Delete Route Table
    ec2_vpc_route_table:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      region: "ap-southeast-2"
      route_table_id: "{{ rt_info.route_tables[0].id }}"
      lookup: id
      state: absent

  - name: Delete Internet Gateway
    ec2_vpc_igw:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      vpc_id: "{{ vpc_info.vpcs[0].vpc_id }}"
      state: absent
          
  - name: Delete Security Group
    ec2_group:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      name: WEB_SG        
      state: absent

  - name: Delete VPC
    ec2_vpc_net:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      name: vpc_web
      cidr_block: "192.168.0.0/16"
      region: "ap-southeast-2"
      state: absent
