---
- name: Create a host group
  hosts: localhost

  tasks:
  - name: Get EC2 info
    ec2_instance_info:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      filters:
        "tag:Name": web
    register: EC2_info

  - name: Add EC2 instances to the group
    add_host:
      name: "{{ item.public_dns_name }}"
      groups: web_vm
    loop: "{{ EC2_info.instances }}"
    when: item.state.name == "running"

- name: Provision Apache Server
  hosts: web_vm
  
  tasks:
  - become: true
    block:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install apache on ubuntu
      apt:
        name: apache2
        state: latest
        
    - name: Rename the existing html
      command: mv /var/www/html/index.html /var/www/html/index.html_old 

    - name: Copy new index html from S3 bucket
      get_url:
        url: https://timsuntest.s3-ap-southeast-2.amazonaws.com/index.html
        dest: /var/www/html/index.html
