---
- hosts: localhost

  tasks:
  - name: Create a VPC
    ec2_vpc_net:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      name: test_vpc
      cidr_block: "192.168.0.0/16"
      region: "ap-southeast-2"
      state: "{{ state | default('present') }}"
    register: vpc_status
        
  - name: create Public subnet
    ec2_vpc_subnet:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      az: "ap-southeast-2a"
      cidr: "192.168.1.0/24"
      vpc_id: "{{ vpc_status.vpc.id }}"
      map_public: yes
      tags:
        Name: "public"
    register: sub_public
        
  - name: Internet Gateway setup
    ec2_vpc_igw:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      vpc_id: "{{ vpc_status.vpc.id }}"
    register: igw
        
  - name: Public Route Table setup
    ec2_vpc_route_table:
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      region: "ap-southeast-2"
      vpc_id: "{{ vpc_status.vpc.id }}"
      subnets:
      - "{{ sub_public.subnet.id }}"
      routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
